### ISSUE TITLE
dbt metrics

### ISSUE THREAD

**Issue by RobbertDM** [starburstdata/dbt-trino-utils#17]
### Describe the feature

I just tried to use [dbt metrics](https://docs.getdbt.com/docs/build/metrics), but it fails with trino, I think because of the following:
There's a [`dateadd`](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/misc/metrics__date_spine.sql#L52) in the [`metric_date_spine` macro](
https://github.com/dbt-labs/dbt_metrics/blob/main/macros/misc/metrics__date_spine.sql#L28-L73)  in the that trino doesn't recognize (it's [`date_add`](https://trino.io/docs/current/functions/datetime.html#date_add) for trino). 
Would it be an option to use this package to reimplement the macros necessary to run dbt metrics? 

### Describe alternatives you've considered

Overwrite the macros myself

### Who will benefit?

People who want to use dbt metrics with trino.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by RobbertDM** [comment]
What do you think about something like https://github.com/RobbertDM/dbt-trino-metrics ?
There's a choice here: 
1. make a repo for every package we want to provide trino shims for, or
2. use this one as a collection of trino shims for all packages

I'm a bigger fan of 1, because those repositories can be used to merge things upstream more easily.
2 is more convenient for users, as they only need to install a single trino shims package and be covered, + you can re-use some CI and integration test overhead probably.
What do you think?

**Comment by RobbertDM** [comment]
Same goes for https://github.com/RobbertDM/dbt-trino-date, which I needed to make https://github.com/calogica/dbt-expectations work

**Comment by mdesmet** [comment]
I would stick to this repo similar as in dbt lab's [spark-utils](https://github.com/dbt-labs/spark-utils) as it is most convenient from end user perspective.

The work on these is highly appreciated and welcome! I would also suggest evangelizing this on dbt slack to get more people involved.

**Comment by RobbertDM** [comment]
Ah yes, makes sense, with the "compatibility" notice in the README. 

I made 4 repos recently, each with a single shim to make a package work.
* https://github.com/RobbertDM/dbt-trino-date 
* https://github.com/RobbertDM/dbt-trino-metrics 
* https://github.com/RobbertDM/dbt-trino-expectations 
* https://github.com/RobbertDM/dbt-trino-iceberg

I'll make a PR for some of them, but others are too "opinionated" for this package since they do the `timestamp(6)` trickery needed for iceberg.

**Comment by RobbertDM** [comment]
See https://github.com/starburstdata/dbt-trino-utils/pull/19
and https://github.com/starburstdata/dbt-trino-utils/pull/20
